<?php namespace DigitalUnited\VcCleanUp;

class VcStdModules {
    static function get() {
        return [
            'vc_pinterest',
            'vc_custom_heading',
            'vc_message',
            'vc_facebook',
            'vc_tweetmeme',
            'vc_googleplus',
            'vc_raw_html',
            'vc_flickr',
            'vc_progress_bar',
            'vc_pie',
            'vc_wp_tagcloud',
            'vc_separator',
            'vc_text_separator',
            'vc_widget_sidebar',
            'vc_button',
            'vc_button2',
            'vc_cta_button',
            'vc_cta_button2',
            'vc_wp_links',
            'vc_raw_js',
            'vc_wp_posts',
            'vc_wp_categories',
            'vc_wp_archives',
            'vc_wp_rss',
            'vc_wp_search',
            'vc_wp_pages',
            'vc_wp_text',
            'vc_wp_meta',
            'vc_wp_recentcomments',
            'vc_wp_calendar',
            'vc_wp_custommenu',
            'vc_single_image',
            'vc_tour',
            'vc_accordion',
            'vc_carousel',
            'vc_images_carousel',
            'vc_tabs',
            'vc_toggle',
            'vc_gallery',
            'vc_posts_grid',
            'vc_posts_slider',
            'vc_gmaps',
            'vc_video',
            'vc_empty_space',
            'vc_icon',
            'vc_masonry_media_grid',
            'vc_basic_grid',
            'vc_masonry_grid',
            'vc_media_grid',
        ];
    }
}